image: microsoft/dotnet:sdk
pipelines:
  default:
    - step:
        caches:
          - dotnetcore
        script: 
          - export PROJECT_NAME=serverApi.sln
          - export TEST_NAME=test.csproj
          - pwd
          - cd serverApi
          - dotnet restore
          - dotnet build $PROJECT_NAME
          - cd test
          - dotnet test $TEST_NAME
    - step:
        image: node:8.6
        script:
          - ls
          - cd cliente
          - npm install
          - ng build --prod