image: microsoft/dotnet:sdk,node:6.9.4
pipelines:
  default:
    - step:
        caches:
          - dotnetcore
        script: 
          - export PROJECT_NAME=serverApi.sln
          - export TEST_NAME=test.csproj
          - cd serverApi
          - dotnet restore
          - dotnet build $PROJECT_NAME
          - cd test
          - dotnet test $TEST_NAME
    - step:
        script:
          - cd ..
          - cd ..
          - cd client
          - node -v
          - cd ..