sonar.projectKey=gerenciadorpropostas
sonar.projectName=GerenciadorPropostas
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

sonar.sources=serverApi/SRC,cliente-react/src,analytics-worker,notification-worker
sonar.tests=serverApi/tests,serverApi/test

sonar.exclusions=**/bin/**,**/obj/**,**/node_modules/**,**/dist/**,**/*.Designer.cs,**/Migrations/**,**/*.db,**/wwwroot/**,**/*.min.js
sonar.test.inclusions=serverApi/tests/**/*,serverApi/test/**/*

sonar.scm.provider=git
