/**
 * Gerenciador de Propostas API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Categoria } from './categoria';
import { Fornecedor } from './fornecedor';
import { PropostaHistorico } from './propostaHistorico';


export interface PropostaModel {
    nomeProposta?: string;
    descricao?: string;
    valor?: number;
    fornecedor?: Fornecedor;
    propostaHistorico?: Array<PropostaHistorico>;
    categoria?: Categoria;
    status?: PropostaModel.StatusEnum;
    id?: string;
    dataCriacao?: Date;
    dataAtualizacao?: Date;
    excluido?: boolean;
}
export namespace PropostaModel {
    export type StatusEnum = 1 | 2 | 3;
    export const StatusEnum = {
        NUMBER_1: 1 as StatusEnum,
        NUMBER_2: 2 as StatusEnum,
        NUMBER_3: 3 as StatusEnum
    }
}
