/**
 * Gerenciador de Propostas API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PermissaoUsuario } from './permissaoUsuario';


export interface Usuario {
    nome?: string;
    cpf?: string;
    email?: string;
    senha?: string;
    dataNacimento?: Date;
    permissaoUsuario?: PermissaoUsuario;
    id?: string;
    dataCriacao?: Date;
    dataAtualizacao?: Date;
    excluido?: boolean;
}
