/**
 * Gerenciador de Propostas API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface usuarioAuthModel {
  nome?: string;
  email?: string;
  cpf?: string;
  perfil?: usuarioAuthModel.PerfilEnum;
  dataNacimento?: Date;
  id?: string;
  excluido?: boolean;
}
export namespace usuarioAuthModel {
  export type PerfilEnum = 1 | 2 | 3 | 4;
  export const PerfilEnum = {
      NUMBER_1: 1 as PerfilEnum,
      NUMBER_2: 2 as PerfilEnum,
      NUMBER_3: 3 as PerfilEnum,
      NUMBER_4: 4 as PerfilEnum
  }
}
